### ISSUE TITLE
404 while npm install of "textlint-rule-spacing"

### ISSUE THREAD

**Issue by KEINOS** [textlint-ja/textlint-rule-preset-ja-spacing#14]
I got the following error while installing the textlint rule "textlint-rule-spacing", which was [mentioned in Wiki](https://github.com/textlint/textlint/wiki/Collection-of-textlint-rule#rule-presets-japanese).

```bash
404 Not Found - GET https://registry.npmjs.org/textlint-rule-spacing - Not found
```

### Produce

To be certain, I used "node:alpine" Docker container.

```shellsession
$ docker run --rm -it --entrypoint /bin/sh node:alpine
/ # cd
~ # npm install --global textlint
/usr/local/bin/textlint -> /usr/local/lib/node_modules/textlint/bin/textlint.js
+ textlint@11.6.3
added 200 packages from 104 contributors in 16.054s
~ # npm install --global textlint-rule-spacing
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/textlint-rule-spacing - Not found
npm ERR! 404 
npm ERR! 404  'textlint-rule-spacing@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-04-21T03_47_56_983Z-debug.log
~ # 
```

### Possible cause

Deprecated from npm in order to be an abandoned repo.

### Possible alternate package

- [textlint-rule-preset-ja-spacing](https://www.npmjs.com/package/textlint-rule-preset-ja-spacing) @  npmjs.com by @azu 
- [Other search results of "textlint-rule-spacing"](https://www.npmjs.com/search?q=textlint-rule-spacing) @ npmjs.com

### Env info

```shellsession
~ # cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.11.5
PRETTY_NAME="Alpine Linux v3.11"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"

~ # node --version
v13.13.0

~ # npm --version
6.14.4

~ # textlint --version
v11.6.3
```

**Comment by azu** [comment]
`textlint-rule-spacing` is repository name.
`textlint-rule-preset-ja-spacing` is rule preset name.

To less confuse, We'll change repository name to `textlint-rule-preset-ja-spacing`.

**Comment by KEINOS** [comment]
@azu 

Thank you for the quick response! I under stood.

So, I suppose the wiki in textlint needs to be changed as well to avoid 404.

**Comment by KEINOS** [comment]
And it was already fixed. Quick job! :+1:
