### ISSUE TITLE
プリセットに含まれるすべてのルールを有効にする方法の説明を改善して欲しい

### ISSUE THREAD

**Issue by kyanny** [textlint-ja/textlint-rule-preset-ja-spacing#24]
[README.md](https://github.com/textlint-ja/textlint-rule-preset-ja-spacing/blob/master/README.md) の [デフォルト設定](https://github.com/textlint-ja/textlint-rule-preset-ja-spacing/blob/master/README.md#%E3%83%87%E3%83%95%E3%82%A9%E3%83%AB%E3%83%88%E8%A8%AD%E5%AE%9A)の項目にはには以下のように記載されています。

> 次のように設定することで、プリセットに含まれるすべてのルールを有効にできます。

```json
{
    "rules": {
        "preset-ja-spacing": {
            "ja-space-around-code": {
                "before": false,
                "after": false
            }
        }
    }
}
```

しかし、上記の設定では `ja-space-between-half-and-full-width` は有効になりません（[検証用プロジェクト](https://github.com/kyanny/test-textlint-rule-preset-ja-spacing)）。
（なお、ここでは「有効になる」を「スペースを常に入れる（"space":"always"）」の状態という意味であると解釈しています）

`ja-space-between-half-and-full-width` は .textlintrc 内で明示的に有効する必要があるのだと思いますが、これは README.md の記載内容と一致していないので、ドキュメントを修正して欲しいです。

**Comment by azu** [comment]
>  （なお、ここでは「有効になる」を「スペースを常に入れる（"space":"always"）」の状態という意味であると解釈しています）

いえ、`ja-space-around-code`のデフォルト値が`false`なので、設定することで`ja-space-around-code`を有効化できるという意味合いですね。(`ja-space-around-code`はpresetに含まれていますが、デフォルトが無効であるという話ですね)。

**Comment by azu** [comment]
https://github.com/textlint-ja/textlint-rule-preset-ja-spacing/commit/ff66db25da212b8c087c7bfaf3646f4990338658 でREADMEを更新しました。

**Comment by kyanny** [comment]
なるほど、掛っている対象を読み間違えていたようです。更新後の README は理解しやすくなりました。ありがとうございました！
