### ISSUE TITLE
半角文字と全角文字にスペースを入れるかどうかのルールで、数字のみ無効にする設定が欲しい

### ISSUE THREAD

**Issue by uhooi** [textlint-ja/textlint-rule-preset-ja-spacing#40]
`textlint-rule-ja-space-between-half-and-full-width` ルールは、デフォルトでアルファベットと数字の両方に適用されます。
https://github.com/textlint-ja/textlint-rule-preset-ja-spacing/tree/master/packages/textlint-rule-ja-space-between-half-and-full-width

アルファベットのみ適用し、数字は無視する設定が欲しいです。

例

適用前

```markdown
## テスト

2022年7月7日、本日は晴天なり。
りんごは英語でAppleという。
```

適用後

```markdown
## テスト

2022年7月7日、本日は晴天なり。
りんごは英語で Apple という。
```

このように「2022年7月7日」はそのままで、「Apple」の前後のみに半角スペースを入れたいです。

**Comment by Sean0628** [comment]
オプションにスペースを入れる対象の配列を指定できるようになりました。

Refs: [v2.3.0](https://github.com/textlint-ja/textlint-rule-preset-ja-spacing/releases/tag/v2.3.0)

```json
{
    "rules": {
        "ja-space-between-half-and-full-width": {
            "space": ["alphabets"]
        }
    }
}
```

```sh
>>> cat old.md
## テスト

2022年7月7日、本日は晴天なり。
りんごは英語でAppleという。

>>> cat old.md | npx textlint --stdin --stdin-filename README.md --fix --format fixed-result --output-file new.md

>>> cat new.md
## テスト

2022年7月7日、本日は晴天なり。
りんごは英語で Apple という。
```

**Comment by uhooi** [comment]
なんと…！？ご対応ありがとうございます、嬉しいです🙇
